### ISSUE TITLE
Issue with laravel v5.2.32

### ISSUE THREAD

**Issue by go-nut** [jgrossi/corcel#151] opened 2016-05-18 19:56 UTC
When upgrading to laravel v5.2.32 from v5.2.31 I get an error.

When doing a composer update I noticed the version of laravel changed.  Upon doing nothing but changing the version of laravel I get the following error.

```
ErrorException in Model.php line 3467:
Undefined property: App\Model\Post::$meta

ErrorException in Model.php line 3467:
Undefined property: App\Model\Post::$meta

in Model.php line 3467
at HandleExceptions->handleError('8', 'Undefined property: App\Model\Post::$meta', '/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php', '3467', array('key' => 'meta', 'this' => object(Post))) in Model.php line 3467
at Model->__isset('meta') in Post.php line 198
at Post->__get('meta') in Post.php line 199
at Post->__get('softDelete') in Post.php line 182
at Post->newQuery() in Model.php line 3498
at Model->__call('taxonomy', array('category', 'learn'))
at Post->taxonomy('category', 'learn')
at call_user_func_array(array(object(Post), 'taxonomy'), array('category', 'learn')) in Model.php line 3514
at Model::__callStatic('taxonomy', array('category', 'learn')) in BlogController.php line 20
at Post::taxonomy('category', 'learn') in BlogController.php line 20
at BlogController->home()
at call_user_func_array(array(object(BlogController), 'home'), array()) in Controller.php line 80
at Controller->callAction('home', array()) in ControllerDispatcher.php line 146
at ControllerDispatcher->call(object(BlogController), object(Route), 'home') in ControllerDispatcher.php line 94
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
```

If I downgrade back to v5.2.31 the error goes away.  I was in a rush to finish a project for a client so I just downgraded laravel, but I figured I would post here in case anybody else runs into the same issue.

**Comment by jgrossi** [comment] 2016-05-18 20:43
Hi @go-nut! Sorry about that :-( I think if you're using `->meta` you want to get all the meta fields, right? 
Did you try `->meta()->get()`? Best regards.

**Comment by manogi** [comment] 2016-05-19 14:24
I get the same error - I don't even use `->meta`, I just call something like `Page::find($id)`. Happens on all calls like this. Something is seriously broken - when updating to v5.2.32.

**Comment by jgrossi** [comment] 2016-05-19 14:33
We're checking this now :-) thanks @manogi

**Comment by jgrossi** [comment] 2016-05-19 14:45
@manogi I updated the `dev` branch. Can you check if it's working, please?

**Comment by manogi** [comment] 2016-05-19 14:51
Now it says: `Undefined property: App\Page::$thumbnail`
so one step further, I guess ;-)

**Comment by jgrossi** [comment] 2016-05-19 14:57
But what are you trying to get? Where is the error triggering?

**Comment by manogi** [comment] 2016-05-19 15:09
I am just trying to get a Page with `Page::published()->slug($slug)->first()`

When I add `if(isset($this->thumbnail))`

and `if(isset($this->taxonomies))`

in your src/Post.php, it seems to work:

```
public function getImageAttribute()
    {
        if(isset($this->thumbnail)){
            if ($this->thumbnail and $this->thumbnail->attachment) {
                return $this->thumbnail->attachment->guid;
            }
        }
    }

  function getTermsAttribute()
    {

        $terms = [];
        if(isset($this->taxonomies)){
            $taxonomies = $this->taxonomies;
            

            foreach ($taxonomies as $taxonomy) {
                $taxonomyName = $taxonomy['taxonomy'] == 'post_tag' ? 'tag' : $taxonomy['taxonomy'];
                $terms[$taxonomyName][$taxonomy->term['slug']] = $taxonomy->term['name'];
            }
        }
        return $terms;
    }
```

**Comment by jgrossi** [comment] 2016-05-19 15:20
@manogi can you test again using the updated `dev` branch? thanks

**Comment by manogi** [comment] 2016-05-19 15:24
We are getting there: now it says
`ErrorException in Post.php line 469:
Invalid argument supplied for foreach()`

It seems `$this->terms` is not defined yet there

**Comment by jgrossi** [comment] 2016-05-19 15:52
@manogi can you try again? I hope everything is fixed now :-)

**Comment by manogi** [comment] 2016-05-19 15:58
Not at the computer anymore but will try to test it later this evening -- thank you!

**Comment by jgrossi** [comment] 2016-05-19 16:07
No problem @manogi thanks you!

**Comment by jgrossi** [comment] 2016-05-19 18:30
@go-nut Corcel was updated to fix this issue. Please install version 1.0.9 and let me know if the problems were fixed. Thanks!

**Comment by manogi** [comment] 2016-05-19 19:00
@jgrossi, for me there is still one issue: it says 
```
ErrorException in Post.php line 488:
implode(): Invalid arguments passed
````

when I do this in your src/Post.php:
```
public function getKeywordsStrAttribute()
    {
        if(is_array($this->keywords)){
            return implode(',', $this->keywords);
        }
    }
````
it seems to be fine.

**Comment by manogi** [comment] 2016-05-19 19:00
@jgrossi, for me there is still one issue: it says 
```
ErrorException in Post.php line 488:
implode(): Invalid arguments passed
````

when I do this in your src/Post.php:
```
public function getKeywordsStrAttribute()
    {
        if(is_array($this->keywords)){
            return implode(',', $this->keywords);
        }
    }
````
it seems to be fine.

**Comment by jgrossi** [comment] 2016-05-19 19:10
@manogi can you send a PR including a test in `tests\TaxonomyTest.php`?

**Comment by manogi** [comment] 2016-05-20 11:30
@jgrossi I sent a PR to dev - hope that's right

**Comment by QWp6t** [comment] 2016-05-20 13:47
@jgrossi 

New installation of Laravel, implemented Corcel.

```php
Route::get('blog', function () {
    return \App\WordPress\Post::all();
});
```
Returns:
> Undefined property: `App\WordPress\Post::$thumbnail`

Let me know if there's anything I can do to help.

**Comment by jgrossi** [comment] 2016-05-20 13:49
Hi @QWp6t! Thanks for the support. Are you using Corcel `v1.0.9`?

**Comment by QWp6t** [comment] 2016-05-20 13:52
Yep. I just double-checked composer.lock to confirm. It's 1.0.9.

**Comment by jgrossi** [comment] 2016-05-20 14:01
@QWp6t I just made a test using Laravel 5.2.32 and Corcel 1.9.2 calling `App\Post::all()` and no error.
Can you paste here more information about the error, the lines where it's being triggered? Thanks ;-)

**Comment by QWp6t** [comment] 2016-05-20 14:13
I've narrowed down the cause of the issue.

It's this change in Eloquent. Manually reverting this change resolves the issue: https://github.com/laravel/framework/commit/45fb88125fc931127804c1da111b72798565e9a7

I'm guessing that you're not using PHP 7, which is why you're not experiencing the same issue. Is that correct?

**Comment by jgrossi** [comment] 2016-05-20 14:16
@QWp6t I'm using PHP7 `PHP 7.0.2-4+deb.sury.org~trusty+1 (cli) ( NTS )`. All Corcel tests are passing here and the Laravel app too. Can you give me more information about the error?

**Comment by QWp6t** [comment] 2016-05-20 14:22
Sure thing, here's the stack trace...
```
Undefined property: App\WordPress\Post::$thumbnail

1. in Model.php line 3467
2. at HandleExceptions->handleError('8', 'Undefined property: App\WordPress\Post::$thumbnail', '/srv/www/example.com/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php', '3467', array('key' => 'thumbnail', 'this' => object(Post))) in Model.php line 3467
3. at Model->__isset('thumbnail') in Post.php line 208
4. at Post->__get('thumbnail') in Post.php line 422
5. at Post->getImageAttribute(null) in Model.php line 2720
...
```

Also, @manogi submitted a failing test that demonstrates this same issue.

**Comment by rundef** [comment] 2016-05-20 14:49
It seems to me that since the laravel change mentioned by @QWp6t , we now have to call **$model->relation()** rather than **$model->relation**, eg: **$page->thumbnail()** instead of **$page->thumbnail**.

**Comment by manogi** [comment] 2016-05-20 15:48
I begin to think that there is a problem with this method in Eloquent/Model.php.
The problem occurs because it was not checked if `$this->$key` is set in this method - maybe it is not a Corcel but an Eloquent problem???

```

public function __isset($key)
    {
        if (isset($this->attributes[$key]) || isset($this->relations[$key])) {
            return true;
        }

        if (method_exists($this, $key) && $this->$key && isset($this->relations[$key])) {

            return true;
        }

        return $this->hasGetMutator($key) && ! is_null($this->getAttributeValue($key));
    }

```

**Comment by rundef** [comment] 2016-05-20 16:15
See PR #159

**Closed** 2016-06-01 18:55 UTC
